version: '3.8'
services:
  mysql:
    image: postgres:latest
    container_name: cosmo_cats_db
    environment:
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: cosmo_caTS
      POSTGRES_USERNAME: ronaldo2017
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql

volumes:
  db_data:
